name: Run Tests

on:
  push:
    branches: [main]

jobs:
  check-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for test_main.py
        run: |
          if [ ! -f test_main.py ]; then
            echo "Test file not found!" > napaka.txt
            exit 1
          fi

      - name: Upload napaka.txt
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-status
          path: napaka.txt

  run-tests:
    needs: check-tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download napaka.txt
        uses: actions/download-artifact@v3
        with:
          name: test-status

      - name: Check for error file
        run: |
          if grep -q "not found" napaka.txt; then
            echo "Tests failed to load."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python3 -m unittest test_main.py