name: Razmestitev kode

# Proženje po uspešnem zaključku testnega delovnega toka
on:
  workflow_run:
    workflows: ["Testiranje kode"] # Povezava z vašim testnim workflow-om
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    # Zažene se le, če je testni workflow uspešen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted # Uporaba self-hosted runnerja, kot v test.yml
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        # Prenos kode iz repozitorija za gradnjo Docker slike

      - name: Priprava Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Namestitev Buildx za gradnjo Docker zabojnikov na self-hosted runnerju

      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${ secrets.DOCKERHUB_USERNAME }
          password: ${ secrets.DOCKERHUB_TOKEN }
        # Prijava v DockerHub z uporabo GitHub skrivnosti

      - name: Gradnja in potiskanje Docker slike
        uses: docker/build-push-action@v6
        with:
          context: . # Uporaba trenutnega direktorija za Dockerfile
          push: true # Potiskanje slike na DockerHub
          tags: ${ secrets.DOCKERHUB_USERNAME }/moja-aplikacija:latest
		  