name: Testiranje kode

on:
  push:
    branches: [ main ]

jobs:
  preveri-teste:
    runs-on: ubuntu-latest
    outputs:
      testi_obstajajo: ${{ steps.preveri.outputs.obstajajo }}
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        # Prenos kode iz repozitorija za dostop do datotek

      - name: Preveri če obstajajo testne skripte
        id: preveri
        run: |
          touch napaka.txt
          if [ -d "./tests" ] && ls ./tests/test_*.py 1> /dev/null 2>> napaka.txt; then
            echo "obstajajo=true" >> $GITHUB_OUTPUT
            echo "Testi so najdeni." >> napaka.txt
          else
            echo "obstajajo=false" >> $GITHUB_OUTPUT
            echo "Testne skripte manjkajo!" >&2
            echo "NAPAKA: Testne skripte manjkajo!" >> napaka.txt
            exit 1
          fi
        # Preverjanje obstoja testnih datotek; standardna napaka se preusmeri v napaka.txt

      - name: Naloži artefakte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-status
          path: napaka.txt
        # Artefakt napaka.txt se naloži za komunikacijo z drugim poslom

  poganjanje-testov:
    needs: preveri-teste
    runs-on: ubuntu latest
    if: needs.preveri-teste.outputs.testi_obstajajo == 'true'
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
        # Matrika za testiranje na različnih verzijah Pythona
      fail-fast: false  # Nadaljuje z drugimi verzijami, tudi če ena pade
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        # Ponoven prenos kode za drugi posel

      - name: Prenesi artefakte
        uses: actions/download-artifact@v4
        with:
          name: test-status
        # Prenos artefakta napaka.txt iz prvega posla

      - name: Nastavi Python verzijo
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        # Komentar: Zagotovi, da je pravilna verzija Pythona na voljo

      - name: Nastavi virtualno okolje in poženite teste (matrix)
        run: |
          if grep -q "NAPAKA" napaka.txt; then
            echo "Napaka pri preverjanju testov!"
            exit 1
          fi
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pytest tests/ --verbose