name: Razmestitev kode

on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4
        # Komentar: Prenos kode iz repozitorija za gradnjo Docker slike

      - name: Priprava Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Komentar: Namestitev Buildx za gradnjo Docker zabojnikov na self-hosted runnerju

      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Komentar: Prijava v DockerHub z uporabo GitHub skrivnosti

      - name: Gradnja in potiskanje Docker slike
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
          # Komentar: Ime slike prilagojeno projektu; spremenite 'my-python-app' glede na vaše potrebe